language: java
services:
  - docker

before_install:
  - ./scripts/travis.sh

install:
  - pyenv global 3.8.1
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .
  - sudo cp ./rayvens/linux-x86_64/kamel /usr/local/bin/kamel

script:
  - python ./examples/travis/topic.py
  - python ./examples/travis/source.py
  - ./scripts/start-kind.sh
  - ray submit ./scripts/cluster.yaml ./examples/travis/topic.py
  - ray submit ./scripts/cluster.yaml ./examples/travis/source.py
