language: python
services:
  - docker

python:
  - 3.8

before_install:
  - ./scripts/travis.sh

install:
  - pip install -r requirements.txt
  - pip install rayvens

script:
  - ./scripts/start-kind.sh
  - ray submit ./scripts/cluster.yaml ./examples/pubsub.py
