language: java
services:
  - docker

before_install:
  - ./scripts/travis.sh

install:
  - pyenv global 3.8.1
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .

script:
  - ./scripts/start-kind.sh
  - python ./examples/travis/stream-local.py
  - python ./examples/travis/source-local.py
  - ray submit ./scripts/cluster.yaml ./examples/travis/stream.py
  - ray submit ./scripts/cluster.yaml ./examples/travis/source.py
  - ray submit ./scripts/cluster.yaml ./examples/travis/source_operator.py
