apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  serviceName: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zk
          image: docker.io/zookeeper:3.5
          ports:
            - name: zookeeper
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          livenessProbe:
            tcpSocket:
              port: 2181
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "echo ruok | nc -w 1 localhost 2181 | grep imok"
          env:
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "srvr,ruok"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  serviceName: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command:
            [
              "sh",
              "-c",
              'result=1; until [ $result -eq 0 ]; do OK=$(echo ruok | nc -w 1 zookeeper 2181); if [ "$OK" == "imok" ]; then result=0; echo "zookeeper returned imok!"; else echo waiting for zookeeper to be ready; sleep 1; fi; done; echo "Success: zookeeper is up"',
            ]
      containers:
        - name: kafka
          image: docker.io/wurstmeister/kafka:2.13-2.6.0
          ports:
            - name: kafka-internal
              containerPort: 9092
            - name: kafka-external
              containerPort: 9093
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            exec:
              command:
                - /opt/kafka/bin/kafka-topics.sh
                - localhost:9092
                - --version
          env:
            - name: HOSTNAME_COMMAND
              value: hostname -f
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INCLUSTER:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_LISTENERS
              value: INCLUSTER://:9092,EXTERNAL://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INCLUSTER://_{HOSTNAME_COMMAND}:9092,EXTERNAL://localhost:31093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INCLUSTER
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_PORT
              value: "9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  selector:
    name: kafka
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
    - name: kafka-external
      port: 9093
      targetPort: 9093
      nodePort: 31093
