kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://registry:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
      endpoint = ["http://registry:5000"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31093
        hostPort: 31093
        protocol: TCP
      - containerPort: 31095
        hostPort: 31095
        protocol: TCP
