kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5000"]
      endpoint = ["http://host.docker.internal:5000"]
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 31095
    hostPort: 31095
    protocol: TCP